### ISSUE TITLE
[bug] dynaconf[vault] fails with new hvac

### ISSUE THREAD

**Issue by lpramuk** [dynaconf/dynaconf#807]
**Describe the bug**
dynaconf[vault] is not able to work with new `hvac` 1.0.0+
`DeprecationWarning` turned into `AttributeError`

This:
```
DeprecationWarning: Call to deprecated function 'auth_approle'. This method will be removed in version '0.12.0' Please use the 'login' method on the 'hvac.api.auth_methods.approle' class moving forward.
```
into this:
```
AttributeError: 'Client' has no attribute 'auth_approle'
```

**To Reproduce**

1. Use unpinned hvac (1.0.0+) - dynaconf[vault] dependency
